### ISSUE TITLE
a

### ISSUE THREAD

**Issue by n8901** [ooxymoron/oxide#3]
23  ~                 y) += $e.height() + 8
    |

error: ambiguous outer attributes
  --> src/draw/component/movement_window.rs:20:17
   |
20 | /                 #[allow(unused_assignments)]
21 | |                 y += $e.height() + 8
   | |____________________________________^
...
25 |           a!(Checkbox::new("bhop", s!().movement.bhop.clone(), 10, y));
   |           ------------------------------------------------------------ in this macro invocation
   |
   = note: this error originates in the macro `a` (in Nightly builds, run with -Z macro-backtrace for more info)
help: wrap the expression in parentheses
   |
20 ~                 (#[allow(unused_assignments)]
21 ~                 y) += $e.height() + 8
   |

error: ambiguous outer attributes
  --> src/draw/component/movement_window.rs:20:17
   |
20 | /                 #[allow(unused_assignments)]
21 | |                 y += $e.height() + 8
   | |____________________________________^
...
26 |           a!(Checkbox::new("autostrafe", s!().movement.autostrafe.clone(), 10, y));
   |           ------------------------------------------------------------------------ in this macro invocation
   |
   = note: this error originates in the macro `a` (in Nightly builds, run with -Z macro-backtrace for more info)
help: wrap the expression in parentheses
   |
20 ~                 (#[allow(unused_assignments)]
21 ~                 y) += $e.height() + 8
   |

warning: the feature `absolute_path` has been stable since 1.79.0-nightly and no longer requires an attribute to enable
 --> src/lib.rs:9:5
  |
9 |     absolute_path
  |     ^^^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: the feature `pointer_is_aligned` has been stable since 1.79.0-nightly and no longer requires an attribute to enable
 --> src/lib.rs:3:5
  |
3 |     pointer_is_aligned,
  |     ^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'pointer_is_aligned_to'
   --> src/sdk/entity/mod.rs:169:49
    |
169 |             if !(rend as *const _ as *const u8).is_aligned_to(8) {
    |                                                 ^^^^^^^^^^^^^
    |
    = note: see issue #96284 <https://github.com/rust-lang/rust/issues/96284> for more information
    = help: add `#![feature(pointer_is_aligned_to)]` to the crate attributes to enable
    = note: this compiler was built on 2024-04-25; consider upgrading it if it is out of date

For more information about this error, try `rustc --explain E0658`.
warning: `oxide` (lib) generated 2 warnings
error: could not compile `oxide` (lib) due to 35 previous errors; 2 warnings emitted
failed to build oxide

**Comment by n8901** [comment]
./toolbox.py start_tf2

AppFramework : Unable to load module engine.so!
Unable to load interface VCvarQuery001 from engine.so

**Comment by ooxymoron** [comment]
fixed in 15988b59f5ef73452c74cfbb6cf2582aee120fc9
